#/bin/sh

echo "DEFINE QLOCAL(ADM.EVENTS) CLUSTER(ESB)" | runmqsc ADM

echo "DEFINE SUB(ALL) TOPICSTR('#') PSPROP (RFH2) DEST(ADM.EVENTS) DESTQMGR(ADM)" | runmqsc ESB
echo "DEFINE SUB(ALL) TOPICSTR('#') PSPROP (RFH2) DEST(ADM.EVENTS) DESTQMGR(ADM)" | runmqsc INT
echo "DEFINE SUB(ALL) TOPICSTR('#') PSPROP (RFH2) DEST(ADM.EVENTS) DESTQMGR(ADM)" | runmqsc EXT
