#/bin/sh

echo "DEFINE LISTENER (ESB.LISTENER) TRPTYPE (TCP) CONTROL (QMGR) PORT (1414)" | runmqsc ESB
echo "DEFINE LISTENER (INT.LISTENER) TRPTYPE (TCP) CONTROL (QMGR) PORT (1415)" | runmqsc INT
echo "DEFINE LISTENER (EXT.LISTENER) TRPTYPE (TCP) CONTROL (QMGR) PORT (1416)" | runmqsc EXT
echo "DEFINE LISTENER (ADM.LISTENER) TRPTYPE (TCP) CONTROL (QMGR) PORT (1417)" | runmqsc ADM

echo "START LISTENER(ESB.LISTENER)" | runmqsc ESB
echo "START LISTENER(INT.LISTENER)" | runmqsc INT
echo "START LISTENER(EXT.LISTENER)" | runmqsc EXT
echo "START LISTENER(ADM.LISTENER)" | runmqsc ADM
