serverConfVersion: 1

defaultQueueManager: 'ADMIN'

Log:
  eventLog: '/ace/servers/01_ADMIN/log/event.txt'

RestAdminListener:
  port: 7601

ResourceManagers:
  JVM:
    jvmDebugPort: 7901      
  HTTPConnector:
    ListenerPort: 7801 
  ActivityLogManager:
    activityLogEnabled: true
    defaultLogSizePerThread: 1000
    minSeverityLevel: 'INFO'    
  ExceptionLog:
    enabled: true             
    includeFlowThreadReporter: true 
    showNestedExceptionDetails: true  