serverConfVersion: 1

defaultQueueManager: 'APP'

RestAdminListener:
  port: 7602

Log:
  consoleLog: false         
  outputFormat: 'idText'  
  eventLog: '/ace/servers/02_esb/events/events.txt' 

AdminLog:
  enabled: true         
  fileLog: true           
  fileLogRetentionPeriod: 1    
  fileLogCountDaily: 1   
  fileLogSize: 100              
  consoleLog: false             

Events:
  OperationalEvents:
    MQ:
      enabled: true
      format: 'xml'   
  BusinessEvents:
    MQ:
      enabled: true
      format: 'xml'    
  AdminEvents:
    MQ:
      enabled: true    
      format: 'xml'  

ActivityLog:
  Activities:
    enabled: true                  
    minSeverityLevel: debug  
    fileName: '/ace/servers/02_esb/activity/activity.txt' 
    numberOfLogs: 4                
    maxAgeMins: 60                 
    maxFileSizeMb: 100            
    formatEntries: true     

Monitoring:
  MessageFlow:
    publicationOn: 'active'
    eventFormat: 'MonitoringEventV2'

Statistics:
  Archive:
    archivalOn: 'active'
    accountingOrigin: 'basic'  
    majorInterval: 10
    nodeDataLevel: 'basic'     
    outputFormat: 'xml'   
    threadDataLevel: 'basic'
  Snapshot:
    publicationOn: 'active'  
    accountingOrigin: 'basic' 
    nodeDataLevel: 'basic'     
    outputFormat: 'xml'    
  Resource:
    reportingOn: true       
    outputFormat: 'file'    
     
ResourceManagers:
  JVM:
    jvmDebugPort: 7902     
  HTTPConnector:
    ListenerPort: 7802
  ActivityLogManager:
    activityLogEnabled: true
    defaultLogSizePerThread: 1000
    minSeverityLevel: 'debug'    
  ExceptionLog:
    enabled: true             
    includeFlowThreadReporter: true 
    showNestedExceptionDetails: true    