serverConfVersion: 1

defaultQueueManager: 'ADMIN'

Log:
  consoleLog: false         
  outputFormat: 'idText'  
  eventLog: '/ace/servers/03_admin/events/events.txt' 

Statistics:
  Snapshot:
    publicationOn: 'inactive'  
  Archive:
    archivalOn: 'inactive' 
  Resource:
    reportingOn: false

Monitoring:
  MessageFlow:
    publicationOn: 'inactive'

RestAdminListener:
  port: 7603

ResourceManagers:
  JVM:
    jvmDebugPort: 7903      