serverConfVersion: 1

defaultQueueManager: 'EXT'

RestAdminListener:
  port: 7603

Log:
  consoleLog: false  
  outputFormat: 'idText'   
  eventLog: '/ace/servers/03_EXT/events/events.txt' 

AdminLog:
  enabled: true            
  fileLog: true            
  fileLogRetentionPeriod: 1
  fileLogCountDaily: 1     
  fileLogSize: 100              
  consoleLog: false             

Events:
  OperationalEvents:
    MQ:
      enabled: true
      format: 'xml'   
  BusinessEvents:
    MQ:
      enabled: true
      format: 'xml'    
  AdminEvents:
    MQ:
      enabled: true    
      format: 'xml'  

ActivityLog:
  Activities:
    enabled: true                  
    minSeverityLevel: debug  
    fileName: '/ace/servers/03_EXT/activity/activity.txt' 
    numberOfLogs: 4                
    maxAgeMins: 60                 
    maxFileSizeMb: 100            
    formatEntries: true     

Monitoring:
  MessageFlow:
    publicationOn: 'active'
    eventFormat: 'MonitoringEventV2'

Statistics:
  Archive:
    archivalOn: 'active'
    accountingOrigin: 'basic'  
    majorInterval: 10
    nodeDataLevel: 'basic'     
    outputFormat: 'xml'   
    threadDataLevel: 'basic'
  Snapshot:
    publicationOn: 'active' 
    accountingOrigin: 'basic' 
    nodeDataLevel: 'basic'    
    outputFormat: 'xml'    
  Resource:
    reportingOn: true       
    outputFormat: 'file'    
     
ResourceManagers:
  JVM:
    jvmDebugPort: 7903      
  HTTPConnector:
    ListenerPort: 7703
  HTTPSConnector:
    ListenerPort: 7803
  ActivityLogManager:
    activityLogEnabled: true
    defaultLogSizePerThread: 1000
    minSeverityLevel: 'debug'    
  ExceptionLog:
    enabled: true             
    includeFlowThreadReporter: true 
    showNestedExceptionDetails: true    