serverConfVersion: 1

defaultQueueManager: 'APP'

trace: 'diagnostic'               # choose 1 of : none|debug|debugTree|diagnostic|diagnosticTree
traceSize: '1G'             # Set the service trace size
userTrace: 'debugTree'           # choose 1 of : none|debug|debugTree
userTraceSize: '1G'         # Set the user trace size
traceDirectory: '/ace/servers/03_HELLO/log' 

Log:
  eventLog: '/ace/servers/03_HELLO/log/event.txt'

RestAdminListener:
  port: 7603

Events:
  OperationalEvents:
    MQ:
      enabled: true
      format: 'xml'   
  BusinessEvents:
    MQ:
      enabled: true
      format: 'xml'    
    File:
      enabled: true          
      outputFormat: 'xml' 
      filePath: '/ace/servers/03_HELLO/log/businessEvents' 
  AdminEvents:
    MQ:
      enabled: true    
      format: 'xml'  

ActivityLog:
  Activities:
    enabled: true                  
    minSeverityLevel: debug  
    fileName: '/ace/servers/03_HELLO/log/activity' 
    numberOfLogs: 4                
    maxAgeMins: 60                 
    maxFileSizeMb: 100            
    formatEntries: true     

Log:
  consoleLog: true           # Control writing BIP messages to standard out. Set to true or false, default is true.
  outputFormat: 'idText'     # Control the format of BIP messages written to standard out and file. Set to idText, text or ibmjson, default is text if unset.
  eventLog: '/ace/servers/03_HELLO/log/log.txt' 

AdminLog:
  enabled: true                   # Control logging admin log messages. Set to true or false, default is true.
  fileLog: true                  # Control writing admin log messages to file. Set to true or false, default is false.
  fileLogRetentionPeriod: 1      # Sets the number of days to record admin log.
                                   # After this, old files are deleted as new ones are created. Default is 30 days.
  fileLogCountDaily: 1           # Maximum number of admin log files to write per day, default is 10 per day.
  fileLogSize: 100                # Maximum size in MB for each admin log file. Maximum size is 2000MB, default size is 100MB.
  consoleLog: false                # Control writing admin log messages to standard out. Set to true or false, default is false.

Monitoring:
  MessageFlow:
    publicationOn: 'active'
    eventFormat: 'MonitoringEventV2'

Statistics:
  Archive:
    archivalOn: 'active'
    accountingOrigin: 'basic'  
    majorInterval: 5
    nodeDataLevel: 'basic'     
    outputFormat: 'xml'   
    threadDataLevel: 'basic'
  Resource:
    reportingOn: true       
    outputFormat: 'file'    
     
ResourceManagers:
  JVM:
    jvmDebugPort: 7903      
  HTTPConnector:
    ListenerPort: 7803
  ActivityLogManager:
    activityLogEnabled: true
    defaultLogSizePerThread: 1000
    minSeverityLevel: 'debug'    
  ExceptionLog:
    enabled: true             
    includeFlowThreadReporter: true 
    showNestedExceptionDetails: true    