serverConfVersion: 1

defaultQueueManager: 'ADMIN'

Log:
  eventLog: '/var/mqsi/servers/04_TEST_ADMIN/log/event.txt'

RestAdminListener:
  port: 7604

Events:
  OperationalEvents:
    MQ:
      enabled: true
  BusinessEvents:
    MQ:
      enabled: true

Monitoring:
  MessageFlow:
    publicationOn: 'active'
    eventFormat: 'MonitoringEventV2'

Statistics:
  Archive:
    archivalOn: 'active'
    accountingOrigin: 'basic'  
    majorInterval: 5
    nodeDataLevel: 'basic'     
    outputFormat: 'xml'   
    threadDataLevel: 'basic'

ResourceManagers:
  JVM:
    jvmDebugPort: 7904      
  HTTPConnector:
    ListenerPort: 7804
  ActivityLogManager:
    activityLogEnabled: true
    defaultLogSizePerThread: 1000
    minSeverityLevel: 'INFO'    
  ExceptionLog:
    enabled: true             
    includeFlowThreadReporter: true 
    showNestedExceptionDetails: true  